---
extraction:
  cpp:
    prepare:
      packages:
        - flex
        - bison
        - libsqlite3-dev
        - libsctp-dev
        - libradcli-dev
        - libhiredis-dev
        - unixodbc-dev
        - libconfuse-dev
        - libmysqlclient-dev
        - libexpat1-dev
        - libxml2-dev
        - libpq-dev
        - libphonenumber-dev
        - zlib1g-dev
        - libperl-dev
        - libsnmp-dev
        - libdb-dev
        - libldap2-dev
        - libcurl4-gnutls-dev
        - libgeoip-dev
        - libpcre3-dev
        - libmemcached-dev
        - libmicrohttpd-dev
        - librabbitmq-dev
        - liblua5.1-0-dev
        - libncurses5-dev
        - libjson-c-dev
        - uuid-dev
    before_index:
      - export FASTER=1
      - export NICER=0
    index:
      build_command: make exclude_modules="db_oracle osp sngtc cachedb_cassandra cachedb_couchbase cachedb_mongodb auth_jwt" all

