.TH bdb_recover 8 22.11.2009 opensips-berkeley-module "OpenSIPS" 
.\" Process with
.\" groff -man -Tascii bdb_recover.8 
.\"
.SH NAME
bdb_recover \- utility for recovering OpenSIPS db_berkeley files
.SH SYNOPSIS

.B bdb_recover
[
.BI parameters
]

.SH DESCRIPTION
.B bdb_recover
is an utility to recover data from db_berkeley files created by
.B OpenSIPS SIP server
The db_berkeley module uses the Concurrent Data Store (CDS) architecture. As such, no transaction or journaling is provided by the DB natively. The application bdb_recover is specifically written to recover data from journal files that OpenSIPS creates. The bdb_recover application requires an additional text file that contains the table schema.

The schema is loaded with the '\-s' option and is required for all operations. Provide the path to the db_berkeley plain-text schema files. By default, these install to '/usr/local/share/opensips/db_berkeley/opensips/'.

The '\-h' home option is the DB_PATH path. Unlike the Berkeley utilities, this application does not look for the DB_PATH environment variable, so you have to specify it. If not specified, it will assume the current working directory. The last argument is the operation. There are fundamentally only two operations - create and recover. 


.SH FILES
.PD 0
.I /usr/local/share/opensips/db_berkeley/opensips/

.SH USAGE
.TP 12
.B bdb_recover \-s schemadir [\-h home] [\-c tablename]
This will create a brand new DB file with metadata.
.TP

.B bdb_recover \-s schemadir [\-h home] [\-C all]
This will create all the core tables, each with metadata.
.TP

.B bdb_recover \-s schemadir [\-h home] [\-r journal-file]
This will rebuild a DB and populate it with operation from journal-file. The table name is embedded in the journal-file name by convention.
.TP

.B bdb_recover \-s schemadir [\-h home] [\-R lastN]
This will iterate over all core tables enumerated. If journal files exist in 'home', 
a new DB file will be created and populated with the data found in the last N files. 
The files are 'replayed' in chronological order (oldest to newest). This 
allows the administrator to rebuild the db with a subset of all possible 
operations if needed. For example, you may only be interested in 
the last hours data in table location.


.SH NOTES
.PP
A corrupted DB file must be moved out of the way before bdb_recover is executed.

.SH AUTHORS

see 
.B /usr/share/doc/opensips/AUTHORS
.PP
This manual page was written by Alejandro Rios P. <alerios@debian.org>,
based on db_berkeley module's README by Will Quan Copyright (C) 2007 Cisco Systems,
for the Debian project (and may be used by others).

.SH SEE ALSO
.BR opensips(8)
.PP
Full documentation on opensips db_berkeley module is available at /usr/share/doc/opensips-berkeley-module/README.db_berkeley and 
.I https://opensips.org/.
.PP
Mailing lists:
.nf 
users@opensips.org - opensips user community
.nf 
devel@opensips.org - opensips development, new features and unstable version
