.TH opensips-m4cfg 8 17.07.2018 opensips-m4cfg "OpenSIPS" 
.\" Process with
.\" groff -man -Tascii opensips-m4cfg.8 
.\"
.SH NAME
opensips-m4cfg \- utility used by systemd to create the
OpenSIPS configuration file based on the opensips.m4 file.

.SH SYNOPSIS
.B opensips-m4cfg

.SH DESCRIPTION
.B opensips-m4cfg
is a tool used by system to generate the
.B opensips.cfg
configuration file from the
.B opensips.m4 m4 template

.SH AUTHORS

see 
.B /usr/share/doc/opensips/AUTHORS
.PP
This manual page was written by Razvan Crainea <razvan@opensips.org>
based on osipsconsole manpage by Alejandro Rios P. <alerios@debian.org>,
for the Debian project (and may be used by others).

.SH SEE ALSO
.BR opensips(8), opensips.cfg(5)
.PP
Full documentation on opensips is available at
.I https://opensips.org/.
.PP
Mailing lists:
.nf 
users@lists.opensips.org - opensips user community
.nf 
devel@lists.opensips.org - opensips development, new features and unstable version
