.\" $Id$
.TH opensipsunix 8 21.06.2006 opensips "OpenSIPS" 
.\" Process with
.\" groff -man -Tascii opensipsunix.8 
.\"
.SH NAME
opensipsunix \- opensips UNIX socket wrapper
.SH SYNOPSIS
.B opensipsunix
.BI path_to_socket

.SH DESCRIPTION
.B opensipsunix
is a wrapper for sending external commands
.B to OpenSIPS server
via UNIX sockets interface.
.br
This is a binary alternative to the textual FIFO interface.
.PP
.B opensipsunix
reads from standard input one
.B OpenSIPS
command along with its paramters (if any) and prints the response 
to standard output.

.SH PARAMETERS
.TP 3
.B path_to_socket
full path of the UNIX socket file used by OpenSIPS to receive the
external commands

.SH EXAMPLES
.PP
An OpenSIPS commands consists in one ore more lines: first contains the
command name enclosed between ":", the following lines containing the 
command parameters, one per line.
.PP
echo ":uptime:" | opensipsunix /tmp/opensips.sock


.SH AUTHORS

see 
.B /usr/share/doc/opensips/AUTHORS

.SH SEE ALSO
.BR opensips(8), opensips.cfg(5), opensipsctl(8)
.PP
Full documentation on opensips is available at
.I http://www.opensips.org/.
.PP
Mailing lists:
.nf 
users@opensips.org - opensips user community
.nf 
devel@opensips.org - opensips development, new features and unstable version

