CREATE TABLE `ops_report_capture` (
	  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
	  `gid` int(10) unsigned NOT NULL DEFAULT '10',
	  `tss` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  `tsu` int(10) unsigned NOT NULL DEFAULT '0',
	  `transaction_id` varchar(256) NOT NULL DEFAULT '',
	  `correlation_id` varchar(256) NOT NULL DEFAULT '',
	  `source_ip` varchar(60) NOT NULL DEFAULT '',
	  `source_port` int(10) NOT NULL DEFAULT '0',
	  `destination_ip` varchar(60) NOT NULL DEFAULT '',
	  `destination_port` int(10) NOT NULL DEFAULT '0',
	  `capture_ip` varchar(50) NOT NULL,
	  `proto` int(5) NOT NULL DEFAULT '0',
	  `family` int(1) DEFAULT NULL,
	  `type` int(5) NOT NULL DEFAULT '0',
	  `capt_id` int(5) NOT NULL,
	  `node` varchar(125) NOT NULL DEFAULT '',
	  `event` varchar(30) NOT NULL,
	  `payload_len` int(5) NOT NULL DEFAULT '0',
	  `data` varchar(1500) NOT NULL DEFAULT '',
	  PRIMARY KEY (`id`,`tss`),
	  KEY `date` (`tss`),
	  KEY `correlationid` (`transaction_id`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
