# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=registrar.so
# link in common registrar code
misclibs=../../lib/reg/libreg.a

include ../../Makefile.modules
