# $Id$
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=uac.so
misclibs=../../lib/digest_auth/libdigest_auth.a

include ../../Makefile.modules
