#
# Json object manipulation
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=json.so

include ../../lib/json/Makefile.json

include ../../Makefile.modules
