#
# CGRateS billing engine implementation
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=cgrates.so

include ../../lib/json/Makefile.json

include ../../Makefile.modules

