# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=clusterer.so
LIBS=
#DEFS+= -DCLUSTERER_EXTRA_BIN_DBG

include ../../Makefile.modules
