.\" $Id$
.TH opensipsctl 8 21.06.2006 opensips "OpenSIPS" 
.\" Process with
.\" groff -man -Tascii opensipsctl.8 
.\"
.SH NAME
opensipsctl \- opensips control tool
.SH SYNOPSIS
.B opensipsctl
.BI command
[
.BI parameters
]

.SH DESCRIPTION
.B opensipsctl
is a shell script to control
.B OpenSIPS SIP server
It can be used to manage users, domains, aliases and other server options

.SH FILES
.PD 0
.I /etc/opensips/.opensipsctlrc
.br
.I /usr/local/etc/opensips/.opensipsctlrc
.br
.I ~/.opensipsctlrc
.br

.SH COMMANDS
.TP 12
.B \-h
Displays a short usage description, including all available options.
.TP
.B moni
show internal status
.TP
.B ps
show running processes
.TP
.B fifo
send raw FIFO commands
.TP
.B ping <uri>
ping a URI (OPTIONS)
.TP
.B cisco_restart <uri>
restart a Cisco phone (NOTIFY)
.TP 16
.I SUBSCRIBER management:
.TP
.B add <username> <password>
add a new subscriber (*)
.TP
.B passwd <username> <passwd>
change user's password (*)
.TP
.B rm <username>
delete a user (*)
.TP
.B alias show [<alias>]
show aliases
.TP
.B alias rm <alias>
remove an alias
.TP
.B alias add <alias> <uri> 
add an aliases
.TP
.B rpid add <username> <rpid>
add rpid for a user (*)
.TP
.B rpid rm <username>
set rpid to NULL for a user (*)
.TP
.B rpid show <username>
show rpid of a user
.TP
.B alias_db show <alias>
show alias details
.TP
.B alias_db list <sip-id>
list aliases for uri
.TP
.B alias_db add <alias> <sip-id>
add an alias (*)
.TP
.B alias_db rm <alias>
remove an alias (*)
.TP
.B alias_db help
help message
.TP
.B speeddial show <speeddial-id>
show speeddial details
.TP
.B speeddial list <sip-id>
list speeddial for uri
.TP
.B speeddial add <sip-id> <sd-id> <new-uri> [<desc>]
add a speedial (*)
.TP
.B speeddial rm <sip-id> <sd-id>
remove a speeddial (*)
.TP
.B speeddial help
help message
.TP 16
.I AVP management:
.TP
.B avp list [-T table] [-u <sip-id|uuid>] \
[-a attribute] [-v value] [-t type]
list AVPs
.TP
.B avp add [-T table] <sip-id|uuid> \
<attribute> <type> <value>
add AVP (*)
.TP
.B avp rm [-T table]  [-u <sip-id|uuid>] \
[-a attribute] [-v value] [-t type]
remove AVP (*)
.TP
.B avp help
help message
.TP 16
.I ACL (Access Control Lists) management
.TP
.B acl show [<username>]
show user membership
.TP
.B acl grant <username> <group>
grant user membership (*)
.TP
.B acl revoke <username> [<group>]
grant user membership(s) (*)

.TP 16
.I USRLOC (User Location) management
.TP
.B ul show [<username>]
show in-RAM online users
.TP
.B ul rm <username> [<contact URI>]
delete user's UsrLoc entries
.TP
.B ul add <username> <uri>
introduce a permanent UrLoc entry
.TP
.B ul add <username> <uri> <expires>
introduce a temporary UrLoc entry
.TP
.B showdb [<username>]
show online users flushed in DB
.TP 16
.I DOMAIN management
.TP
.B domain show
show list of served domains
.TP
.B domain add <domainname>
add a new served domain
.TP
.B domain rm <domainname>
remove a served domain

.SH NOTES
.PP
Commands labeled with (*) will prompt for a MySQL password.
If the environment variable PW is set, the password will not be prompted.
.PP
IP addresses must be entered in dotted quad format e.g. 1.2.3.4

.SH AUTHORS

see 
.B /usr/share/doc/opensips/AUTHORS

.SH SEE ALSO
.BR opensips(8), opensips.cfg(5)
.PP
Full documentation on opensips is available at
.I http://www.opensips.org/.
.PP
Mailing lists:
.nf 
users@opensips.org - opensips user community
.nf 
devel@opensips.org - opensips development, new features and unstable version

