#
# AKA Authentication - AKA authentication support
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=auth_aka.so
misclibs=../../lib/digest_auth/libdigest_auth.a
include ../../Makefile.modules
