name: notify

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
      job_result:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: false

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: Notify slack fail
        if: ${{ inputs.job_result == 'failure' && github.repository == 'OpenSIPS/opensips' && env.SLACK_BOT_TOKEN != '' }}
        uses: slackapi/slack-github-action@v3.0.3
        with:
          method: chat.postMessage
          token: ${{ env.SLACK_BOT_TOKEN }}
          payload: |
            channel: devel
            text: ":x: ${{ inputs.job_name }} failed in ${{ github.repository }}"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ":x: *${{ inputs.job_name }}* failed in *${{ github.repository }}*"
              - type: context
                elements:
                  - type: mrkdwn
                    text: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Open this run in GitHub Actions>"

      - name: Post Fail
        if: ${{ inputs.job_result == 'failure' }}
        run: |
          echo "💥 \"${{ inputs.job_name }}\" failed – marking workflow 💩" >&2
          exit 1
