# This is a basic workflow to help you get started with Actions

name: Main CI

# Controls when the action will run. 
on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      COMPILER: ${{ matrix.compiler }}
      BUILD_OS: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        compiler: ['gcc', 'clang', 'gcc-9', 'gcc-10', 'clang-9', 'clang-10']
        include:
          - os: ubuntu-22.04
            compiler: 'gcc'
          - os: ubuntu-22.04
            compiler: 'clang'
          - os: ubuntu-22.04
            compiler: 'gcc-11'
          - os: ubuntu-22.04
            compiler: 'gcc-12'
          - os: ubuntu-22.04
            compiler: 'clang-11'
          - os: ubuntu-22.04
            compiler: 'clang-12'
          - os: ubuntu-22.04
            compiler: 'clang-13'
          - os: ubuntu-22.04
            compiler: 'clang-14'
          - os: ubuntu-22.04
            compiler: 'clang-15'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sh -x scripts/build/reset_sources.sh
          sh -x scripts/build/install_depends.sh

      - name: Build
        run: sh -x scripts/build/do_build.sh

      - name: Notify slack fail
        if: failure() && github.repository == 'OpenSIPS/opensips'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: devel
          status: FAILED
          color: danger
